[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Bartosz Baran <bartosz.baran192@gmail.com>"]
license = "Beerware"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "4.2.1"
flake8 = "6.0.0"
flake8-django = "1.3"
black = "23.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py311']
exclude = '''
/(
    | \.git/  # exclude a directory
    | \.mypy_cache/  # exclude a directory
    | \.pytest_cache/  # exclude a directory
    | .*\.pyi?  # exclude generated files
    | .*\.json  # exclude metadata files
    | .*\.md  # exclude documentation
    | .*\.toml  # exclude configuration files
    | .*\.yml  # exclude configuration files
    | .*\.yaml  # exclude configuration files
    | .*\.txt  # exclude configuration files
    | .*\.lock  # exclude configuration files
    | .*\.sh  # exclude configuration files
    | .*\.log  # exclude configuration files
)/
'''
